### PR TITLE
Document steps to deploy concourse to eclipsis with ansible & docker

### PR DESCRIPTION
**Pull request by aguestuser**
* add instructions for creating new eclips.is box
* add ansible host list and instructions for installing ansible on a "control machine"
* add notes and shell commands for manually provisioning eclipsis box with docker and concourse

**GOAL**

* work off of these notes on Monday night to accomplish:
  * the automated provisioning of an eclipsis box with concourse
  * the successful deployment of `intake-form`, `intake-receiver` (and `owncloud`?) to an eclips.is box if tests pass (using ansible and docker for pushing build artifact to prod machine on eclipsis)

### CODE REVIEW

**Comment by aguestuser** [comment]
:100::100::100::100::100::100::100::100::100:
:100: **much excitement!!!**  :100: 
:100::100::100::100::100::100::100::100::100:

spent less than five minutes following Step (4) in the README just now and immediately got a concourse server up, running, and logged into! it just worked! and was *super* simple!

(Now for actually adding some pipelines!)

the login ui:

screenshot_concourse-web-login

screenshot_concourse-web-homepage-no-pipelines

logs on the box:

screenshot_concourse-logs

**Comment by aguestuser** [comment]
couple more steps from the (cool!) CLI and a `hello-world` pipeline is up and running!

screenshot_concourse-cli-setup

screenshot_concourse-web-homepage-hello-world-pipeline

**Comment by gmarceau** [comment]
Sweet, exciting. I'll take a closer look next.

**Comment by gmarceau** [comment]
I'm intrigued by concourse.ci. It seemed very well loved.

**Review by avmcrae — APPROVED** [review]

**Pull request merged**
